// <auto-generated />
namespace ShoppingListTeam3.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixingDataLayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixingDataLayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201605251902378_FixingDataLayer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
